declare module 'electron-devtools-installer'
declare module 'element-ui/lib/locale/lang/zh-CN'
declare module 'element-ui/lib/locale/lang/en'
declare module 'element-ui/lib/locale'
declare module 'vue-touch'
declare module '*.scss'
